version: '2.1'
services:
  config:
    build:
      context: ./config-service
    ports:
      - "8088:8088"
  
  discovery:
    build:
      context: ./discovery-service
    ports:
      - "8061:8061"
  department:
    build:
      context: ./department-service
    ports:
      - "8092:8092"
  employee:
    build:
      context: ./employee-service
    ports:
      - "8090:8090"
      - "9090:9090"
  organisation:
    build:
      context: ./organization-service
    ports:
      - "8091:8091"
#  gateway:
#    build:
#      context: ./gateway-service
#    ports:
#      - "8060:8060"
  zipkin:
    build:
      context: ./zipkin-server
    ports:
      - "9411:9411"
  proxy:
    build:
      context: ./proxy-service
    ports:
      - "8060:8060"